### PR TITLE
Feat/add ship command

### PR DESCRIPTION
**Pull request by anulman**
## Todos before landing

- [ ] Add Windows installer generation
- [x] Add option to skip the packaging step
    - @felixrieseberg thoughts on `--skip-packaging` vs. `--no-package` / `--no-pkg`?
- [ ] Add tests

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Sweet, I <3 it. We might just wire in `electron-builder`, but I'm not sure if that'll be too much work.

**Comment by anulman** [comment]
Sg, will continue down this path.

I agree `electron-builder` would be the ideal path forward, but when I last inspected IIRC it posed architectural issues (e.g. a hard dep on the dual package.json structure?).

Will take another look shortly. For now, this is being used in apps 😄

**Comment by felixrieseberg** [comment]
Yeah, want to just make the current tests pass and we can merge it? Once that happened, I can add windows packaging.

**Comment by anulman** [comment]
Lol, already have that snippet and a test env ready; just needed to clean it up with `options`.

Need to shift attention today, but it's my aim to land this this weekend (so a client can rely on mainline repo vs. my fork!)

**Comment by felixrieseberg** [comment]
I actually merged this puppy. I didn't add anything to the readme yet, but we made a big step :) Again, thanks a ton!

**Comment by bog** [comment]
@felixrieseberg what would electron-builder integration look like here? It has a lot of features I'd hate to rebuild. It looks like a dual package.json structure is no longer required.

**Comment by felixrieseberg** [comment]
That is true - I'd personally love for `electron-builder` to take over most of this stuff. It's probably not even all that hard, I was just tied down with work in other areas (like `electron-windows-store`). If anyone wants to start working on a PR, I'd send <3, commits, and more as help.

**Comment by anulman** [comment]
@bog "builder" work in progress on #129

**Pull request merged**
