### PR TITLE
Move test main.js to ember-electron/test-main.js

### LINKED ISSUE #258: Ember 2.13 Targets Feature question
reference:

[Targets RFC](https://github.com/ember-cli/rfcs/blob/master/complete/0095-standardise-targets.md)

Does this impact ember-electron projects in any way?

Out of the box we are given this configuration:

```
module.exports = {
  browsers: [
    'ie 9',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```

Are there better or more appropriate values to have here?

Thanks.

### PR DESCRIPTION
**Pull request by ursm**
Files in the `tests` directory are transpiled by Babel. Depending on the application's Babel setting, `require()` in test `main.js` may be truncated. Orginally this file does not need to be combined into `assets/tests.js`, so put it outside the `tests` directory.

Closes #258

### CODE REVIEW

**Comment by ursm** [comment]
I have created a test application to reproduce this problem.
https://github.com/ursm/ember-electron-test

Please look at this build output.
https://travis-ci.org/ursm/ember-electron-test/builds/254284528#L279

**Comment by felixrieseberg** [comment]
Thank you, great stuff!

**Comment by felixrieseberg** [comment]
...and released as 2.3.0!

**Comment by bendemboski** [comment]
Sorry, I just got to reading this PR -- doesn't this cause `test-main.js` to be included in the non-test package? Not a super big deal, but also not ideal -- I think it could be easily fixed by excluding `test-main.js` [here](https://github.com/felixrieseberg/ember-electron/pull/284/files#diff-40856518fe99272c3156dc4c0ef1c692R73).

**Comment by ursm** [comment]
@bendemboski 
Certainly, you are right. I opened a new pull request to fix this problem (#287). Thank you for pointing it out!

**Pull request merged**
