### PR TITLE
[WIP] Update testem integration

### PR DESCRIPTION
**Pull request by bendemboski**
## Overview

ember-electron does not play nicely with newer versions of ember-cli and testem. #118 is one example of a bug that exists, but also the code that gets injected into the browser window no longer fully speaks the same language as testem, so even after fixing #118, running in dev mode (`ember electron:test -s`) is kinda funky (it spawns a second testem tab and the results appear there, with the first one remaining blank). Also, ci mode doesn't produce the full set of output (logs and whatnot) that `ember test` produces.

## ~~Open~~ Resolved questions

1. ~~~What kind of backwards compatibility do we need? I can't tell from `ember-try.js` or `package.json` what version of ember-cli this is actually meant to support. I need to investigate, but I suspect with fairly modest effort we can support all released 2.x version (>= 2.3.0 -- earlier 2.x releases never made it out of beta). It will probably take some more significant effort to support 1.13.x.~~~ This supports all released 2.x versions, but not 1.13.
1. ~~~Since we depend on some implementation details of testem, should we pin a version of it in our package.json's dependencies? Would that even work?~~~ We pin a version of testem and make sure the use that pinned version when running `electron:test`.
1. ~~~Can we make a small change to testem to remove the need for our knowledge if its implementation details? I think so, but need to investigate.~~~ My PRs were accepted into testem, so we are no longer assuming any implementation details.

## Benefits of this change

* After a bit of URL re-writing, all communication with testem happens in the same way as it happens when running `ember test` using testem's code, so no custom output parsing/TAP generation, no custom QUnit listening code, and all of the same output is produced as `ember test`.
* The `electron:test` command is now a sub-class of the `ember test` command, and contains very little custom code that needs to be maintained
* The testem configuration is moved to a config file (`/testem-electron.js`) so it can be configured in the same way as `ember test`
* The testem implementation is primed for any of the integrations testem offers (jasmine, mocha, buster)
* When testing, all of the `copy-files` files are included, so modules can be shared between `electron.js` and `tests/electron.js` so tests can run against some form of the main process.

## My next steps

- [x] Test on other ember-cli versions to determine when compatibility breaks
- [x] Gather feedback on which versions we should keep supporting
- [x] Implement support for those version
- [x] Investigate a change that I have in mind that, if merged into testem, would allow us to remove pretty much all of our knowledge of testem's internal implementation
- [x] Write & update unit tests
- [x] Update documentation

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Hey @bendemboski, thank you so much for this well-thought-out PR. It's so fricking good that I just made you a contributor, it seems obvious that everyone using `ember-electron` would benefit greatly from your attention.

To answer your questions:

### 1) Backwards Compatibility
:burn: Everything you need, but not more. I'll gladly merge anything that supports the latest version, even if it breaks older versions. I'm saying this not because I'm a horrible monster, but because I really appreciate the work of contributors - and given that Electron itself lives somewhat on the modern side of JavaScript, I think it's totally fair to assume that people are willing to update their Ember versions.

### 2) Bolt down testem
Maybe? I'm not sure. We might not be able to enforce it using the ember addon infrastructure, but again, if that's what you need, we could make a CLI warning, add it to the readme, or find other ways to help `ember-electron` users understand any need.

### 3) Improve testem
Probably, but I wouldn't know anything about that!

Also:  
> Test on other ember-cli versions to determine when compatibility breaks
> Gather feedback on which versions we should keep supporting
> Implement support for those version
Eeeeeehhh if it's some of the latest ones I think we're good
> Investigate a change that I have in mind that, if merged into testem, would allow us to remove pretty much all of our knowledge of testem's internal implementation
🙏 🙏 🙏 🙏 🙏 
> Write & update unit tests
🙏 🙏 🙏 🙏 
> Update documentation
🙏 🙏 🙏

**Comment by felixrieseberg** [comment]
You should now have the power to merge this yourself (whenever it is ready). Again, thank you so much - and let me know how I can help!

**Comment by bendemboski** [comment]
[Here](https://github.com/testem/testem/pull/1060) is the testem pull request that, if accepted, will allow us to remove our knowledge of testem's implementation details.

**Comment by bendemboski** [comment]
@felixrieseberg I believe this is all ready to go, except I'm waiting for a new release of testem including my changes to support this. If you'd like to take a look at it, feel free, otherwise in a few days or when testem is released (whichever comes later), I'll merge it myself. I'm pretty happy with how it turned out -- it doesn't have any knowledge of testem's internals, and supports all 2.x versions of ember-cli.

I added an 'upgrading' section to the README that assumes that we'll end up tagging this as version 2.0. I'm assuming that because this is a breaking change -- after updating people will need to re-run the blueprint to be able to run tests again. Does that make sense to you?

**Comment by anulman** [comment]
@bendemboski think this will work with #129 ?

**Comment by bendemboski** [comment]
@anulman I don't think it should be a problem. I just did a quick experiment where I rebased my branch onto yours and, after resolving a few conflicts, was able to run tests just fine. So I think we're good.

I'm planning to merge this today unless that will cause you a huge headache. Once I've done so, I'd be happy to rebase your branch onto master and resolve the conflicts (since I just did that and it's fresh in my mind). What do you think?

**Comment by felixrieseberg** [comment]
Sorry, I just saw this - want to rebase this on top of @anulman's work? I'm eager to get all these giant (and impressive) fixes in so that all of us are working on roughly the same code base 😅 

Let me know if you're like "Ugh, Felix just made a ton of merge conflicts for me", in which case I'm happy to do it.

**Comment by bendemboski** [comment]
Nope, I did a test-rebase earlier today and it looks like it should be fine, and I doubt the just-merged stuff will be hard to sort out.

I was thinking that as soon as I can get this ready (hopefully today) I'd merge it, and then rebase @anulman's branch onto master since I have the merge conflicts needing to be resolved fresh in my mind. Unless we want to hold this PR up until #129 is merged, in which case I can rebase the other way and then just wait for #129 to get merged.

**Comment by bendemboski** [comment]
Oh, gotcha, #129 is merged! Yeah, I'll get this rebased shortly...

**Comment by bendemboski** [comment]
This is rebased, and I *think* it works because when I fix all the absolute `require('ember-electron/...')` paths to be relative I can run `ember electron:test` and it passes. But since a whole bunch of mocha tests are failing in master, I can't tell if this PR breaks any functionality that they are supposed to be testing.

**Comment by anulman** [comment]
The lib suite is known to fail (see https://github.com/felixrieseberg/ember-electron/pull/129#issuecomment-281835617) 👍. I have a project known to `:package` & `:make` correctly; will check this evening.

**Comment by felixrieseberg** [comment]
This is neat and should be merged, I'll move it in now. I'll make sure to fix tests before we blast it out to everyone.

Thank you so very much ❤️

**Pull request merged**
