### PR TITLE
Fix package json

### PR DESCRIPTION
**Pull request by bendemboski**
Fixes a few bugs and adds some checks and end-to-end tests so hopefully we'll see fewer blueprint-related regressions.

### CODE REVIEW

**Comment by pichfl** [comment]
If the `.eslintrc.js` files in tests and the blueprint do not work and need to be replaced by the inline comments we can safely remove those files.

**Comment by felixrieseberg** [comment]
Tons of good stuff. Should we just merge this or...?

**Comment by bendemboski** [comment]
Not just yet -- I'm right on the verge of getting it to build on Appveyor...

**Comment by bendemboski** [comment]
Okay @felixrieseberg it looks like this is all good to go. I don't think I have permission to make Appveyor builds run automatically as one of the checks -- can you set that up?

**Comment by felixrieseberg** [comment]
Will set it up!

**Pull request merged**
