### PR TITLE
doc/config Add commented block to allow hash and auto types in config…

### PR DESCRIPTION
**Pull request by dirvine**
…/environment.js.

This is not important and only a convienience

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Looks really nice! One quick question though: I went with Ember's style and used semicolons - could you add those back?

If not, no worries, I can also merge and add them back myself right after.

**Comment by dirvine** [comment]
Ah no prob, just give me 2 mins.

**Comment by dirvine** [comment]
Actually @felixrieseberg  I am not clear what you mean here. Sorry, I was thinking about line endings, but this is not. Perhaps to save time if you want to merge and fix I can see what you mean. otherwise I am happy to change here and push a commit over this if you give me a bit more info.

**Comment by felixrieseberg** [comment]
No worries, I can take care of it. And yes, I just meant the `;` at the end of lines :wink: I don't really care about one code style over the other, but since [ember-cli uses them in their config](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js), I think it'd be fair to keep them around.

**Comment by dirvine** [comment]
Ah thanks for that and sorry for not spotting it. vscode eslint or similar, I must change that setting. 

BTW this is a brilliant project and for newcomers to ember it's really compelling to see the small gap (sans security worries as you spoke about etc.) between the rendering of desktop and web apps. I have never worked in front end so it's pretty new all the MV* stuff and this all helps to see something fast and get a feeling of understanding the differences of desktop/web apps. 

Anyway I just wanted to say thanks. Really neat.

**Comment by felixrieseberg** [comment]
Thanks for your kind words, much appreciated!

**Pull request merged**
